### ISSUE TITLE
Call for Maintainers?

### ISSUE THREAD

**Issue by rschmukler** [rschmukler/agenda#101]
Hey @droppedonjapan, @nwkeeley and @bars3s are any of you guys interested in becoming official maintainers of the project? You handle as many issues as I do, and I appreciate it. Would love to recognize all the work you do.

Also, there are some talks of agenda being incorporated into a major node project, in which case I could definitely use the help as the usage will likely spike, and thus, the issues.

Anyone else who is interested in becoming a maintainer, feel free to throw your hat in the ring in here as well.

**Comment by ilanbiala** [comment]
@rschmukler what major node project is going to use Agenda?

**Comment by ilanbiala** [comment]
Can this be closed now that @nwkeeley and @droppedoncaprica have been added on?
