### ISSUE TITLE
After a period of time, Agenda stops working (resolved, but may still be a bug)

### ISSUE THREAD

**Issue by mcodev1** [rschmukler/agenda#120]
I'm using Agenda 0.6.24 and Sails.js 0.10.5

I'm configuring Agenda like so:

``` js
var Agenda = require('agenda');

var agenda = new Agenda({
    db: sails.config.taskscheduler.connection[process.env.NODE_ENV],
    defaultLockLifetime: 60000
});
```

I have a job that runs once every 30 seconds, and a job that runs once every 5 minutes.

When the jobs run, they run perfectly normally, with no errors, however after it runs the 30 second job exactly 51 times (after 25 minutes, 30 seconds) without issues, both of these jobs remain locked in the database and will not run again until I stop the process and manually unlock the jobs like so:

``` js
        agenda.jobs({ "type": { "!": "normal" } }, function(err, jobs)
        {
[...]
                /*
                 * Unlock all jobs
                 */
                async.each(jobs, function(eachCB)
                {
                    job.attrs.lockedAt = null;
                    job.save(function(err)
                    {
                        if(err)
                        {
                            sails.log.error(err);
                        }
                        eachCB(err);
                    });
                }, done);
[...]
        });
```

After doing this and restarting Agenda, the jobs will then run for another 25 minutes and 30 seconds before halting.

**I found the cause of this being a missing callback within the 5 minute job.** That job was never calling its callback and thus timing out every time. After adding that missing callback, both jobs seem to be working fine without halting.
#### What I don't get:
- Why the 5 minute job was "recovering" from timing out the first 5 times it ran, but then would not run again due to remaining locked.
- Why the 30 second job would stop running after running 51 times. This job correctly was calling its callback.
- Why the `defaultLockLifetime` wasn't working to unlock either of the two jobs after this arbitrary time period.

**Comment by OmgImAlexis** [comment]
@mcodev1 can you confirm this is still an issue? If not can you please close the issue.

**Comment by mcodev1** [comment]
@OmgImAlexis Yes, though like I wrote in the issue, it's pretty confusing behavior in my opinion.
