### ISSUE TITLE
How to restart job after failing?

### ISSUE THREAD

**Issue by skotchio** [rschmukler/agenda#123]
If i get error on my fail handler:

    agenda.on('fail:send email', function(err, job) {
      console.log("Job failed with error: %s", err.message);
    });

then after 'agenda.stop(); agenda.start();` job `send email` will not works anymore. Is it expected behavior and how could start my job after failing again?

**Comment by nwkeeley** [comment]
What I have done in the past is create a custom JobRetry function that will reschedule the job when it fails. This function has exponential back off built in and stores the numberOfRetryAttempts within the data property of the job.

var retryDelay = 5;  /* 5 seconds */
var numberOfRetryAttempts = job.data.numberOfRetryAttempts + 1 || 1;
var nextRunAt = Date.now() + retryDelay * 1000 * Math.pow(2, numberOfRetryAttempts);        

agenda._db.findAndModify({_id: job._id}, {}, {$set: {'data.numberOfRetryAttempts': numberOfRetryAttempts, nextRunAt: new Date(nextRunAt), lastFinishedAt: null, failedAt: null, failReason: null}}, {new: true}, function(err, result) {....

**Comment by BlakePetersen** [comment]
I agree. If there was a reason for failure, it shouldn't try to keep trying something it knows will fail. My problem is, after I have located the problem and addressed it, trying to fire up the same job again doesn't work. The job instances must be removed from the data store before it will work again. 

My feeling is, the behavior should be to stop processing the job on an error until the job has been "redefined".

**Comment by skotchio** [comment]
What if job fails due a temporary reason like database unavailability?

**Comment by nwkeeley** [comment]
See my earlier comment... For things like this I've created my own retry method that is triggered .on fail.  Perhaps "Job Retry" might be a topic worth discussing as a new feature.

**Comment by abdelhady** [comment]
For me, the recurring jobs fail "sometimes" when restarting the server (& of course that prevents it from running anymore which is the problem we are talking about here), it is random, but it happens a lot,
So, I made this workaround which is working fine with me:
````coffeescript
graceful = ()->
	agenda.cancel repeatInterval: { $exists: true, $ne: null }, (err, numRemoved)->
		agenda.stop ()->
			process.exit 0
````
& made [an issue describing the whole thing](https://github.com/rschmukler/agenda/issues/131).

**Comment by droppedoncaprica** [comment]
I think we're running into two separate problems here.  

One is when a job fails (ie returns an error to the `done()` callback or calls `job.fail()`), which then permanently disables the job.

The other issue seems to be if the server shuts down while a job is running, it causes the job to fall into some sort of intermediary state and never gets called again.

**Comment by owenallenaz** [comment]
Regarding jobs stopping on failure, I would like to know if that's intended or unintended behavior. If it's intended, then I would like to propose adding a setting to opt-out of that behavior. If it's unintended, then I'll fix that problem. See my error handling proposal here #172

**Comment by jakeorr** [comment]
@nwkeeley I'm working on adding a custom retry function like you are talking about. When you retry the job are you rescheduling the failed job instance or are you creating a new job with the same data? I have been trying to modify and then reschedule the failed job instance with some weird, inconsistent results. Any insight into how you achieved this would be helpful.

**Comment by sukrit007** [comment]
+1 for supporting retry.

**Comment by omakoleg** [comment]
+1

**Comment by ronenteva** [comment]
Any updates? Is there a workaround to supporting retry of failed jobs?

**Comment by loris** [comment]
Agenda is currently not retrying failed job automatically which makes sense. It is the developper responsibility to decide if the job has to be restarted depending on the error which has been thrown. (You don’t want your server to explode because it is restarting a job indefinitely which failed because of a TypeError in your code...)

To restart a job manually, you can hook on the `fail` event and set a new `nextRunAt`, for instance:

```
agenda.on('fail', (err, job) => {
  if (isErrorTemporary(err)) { // checking that the error is a network error for instance
    job.attrs.nextRunAt = moment().add(10000, 'milliseconds').toDate(); // retry 10 seconds later
    job.save();
  }
});
```

**Comment by jhilden** [comment]
I took a stab at implementing automatic retries in PR #777

@loris is this something you would consider merging?  Then I would put more work into the PR (docs, etc.)

**Comment by Touseef-haider** [comment]
I am also looking for a solution in which i can automate my business logic if something bad happens. @loris's solution seems good.

**Comment by LindoAlien** [comment]
//i found the solution for me works fine. 

function criatejob(req) {
    //create the failCount_ for management the retryes
    req.failCount_ = req.failCount_ + 1
    if (req.failCount_ <= 3) {
        (async () => {
            await agenda.schedule(`${(req.failCount_) * 4} seconds`, "pgto", req);
            console.log("Job successfully saved");
        })();
    } else {
        console.log("rretry 4x - cancell the retry")
    }
}
agenda.define("pgto", async (job, done) => {
    const { wallet, valorpg, texto } = job.attrs.data;
    await PgtoPremio(wallet, texto).then(result => {
        if (result) {
            job.remove(function (err) {
                if (!err) {
                    console.log("Successfully removed job from collection")
                } else {
                    //  console.log(err); //prints null
                };
            });
        }
    });
    done();
})
//listen the FAIL and CreateJob()
agenda.on('fail', function (err, job) {
    console.log(`Job finished failed`);
    createjob(job.attrs.data);
});
 criajob(req.body)
