### ISSUE TITLE
Event for job queued

### ISSUE THREAD

**Issue by jgallen23** [rschmukler/agenda#128]
Is there an event when a job has been queued or added, but not necessarily started?

**Comment by nwkeeley** [comment]
@jgallen23 can you explain your issue a bit more?

You could do:

var agenda = new Agenda({db: { address: 'localhost:27017/agenda-example'}});

agenda.define('do some magic', function(job, done) {
  // some magic
  done()
});

agenda.create('do some magic', {foo: 'bar'}).schedule(someDate).save();

...... This will create a job in the database with a specified nextRunAt time but nothing is going to happen until you call: agenda.start();

**Comment by jgallen23** [comment]
Yep.  Looking for an event when you create a future job that hasn't run yet.  Want to basically have a log of future jobs

**Comment by nwkeeley** [comment]
Currently there is no event emitted when a job is created. A possible solution for you could be to do something like:

agenda.create('do some magic', {foo: 'bar'}).schedule(futureDate).save(function(err) {
// do a custom emit here.
});

**Comment by jgallen23** [comment]
Yeah that'll work. Thanks

**Comment by jgallen23** [comment]
Yeah that'll work. Thanks

**Comment by rschmukler** [comment]
I think the save callback is a fine solution for now, if more people want this use case we can explore an official event.
