### ISSUE TITLE
schedule is not created correctly.

### ISSUE THREAD

**Issue by naumanfarooq** [rschmukler/agenda#138]
Hi,

When we add a new agenda task, the nextRunAt field have tomorrow date. Below is the code we are using.

						models.Agenda.create('post',
						{
							_id: scheduledPost._id
						})
							.schedule(postOn)
							.save(function(err, task){
								if(err){
									cb(err)
								} else {
									models.ScheduledPost.update({
										_id: scheduledPost._id
									}, {
										taskId: task.attrs._id
									}, function(err){
										cb(err, scheduledPost)
									})
								}
							})
					}

we are sending "postOn" variable for scheduling on that day, but it always saves the nextRunAt on tomorrow date.
How can we set a specific date in "NextRunAt"?

**Comment by nwkeeley** [comment]
What is the value of your postOn variable? What is the resulting value in the database. 

Remember dates in the DB are saved in UTC so depending on your timeOffset it may appear to be tomorrow's date.

**Comment by nwkeeley** [comment]
Inactive, closing issue
