### ISSUE TITLE
Task is created but doesn't run

### ISSUE THREAD

**Issue by mplacona** [rschmukler/agenda#139]
Can someone please tell me why this task gets created (and added to the database) but doesn't run?

`agenda.create('send sms message', function(job, done) {`
 
`console.log("hello")`

`}).schedule('now', 'send sms message').unique({'id': event._id}).save();`

I can do pretty much the same thing (except that `unique` doesn't work) with `define`, and the task runs.

While you're here, can you please tell me what the difference is between `create` and `define`?

Thanks in advance

**Comment by nwkeeley** [comment]
@mplacona 

Think of "define" as defining what the job you are going to "create" will do when its processed. You only define a job (or a task definition as some refer to it) once.

Here is a sample:

agenda.define('send sms message', function(job, done) {
   console.log('sending sms message with Event ID', job.attrs.data.event_id);
   done();
});

var event = {
  _id: '123'
}
agenda.create('send sms message', {event_id: event._id}).unique({event_id: event._id}).save();

**Comment by mplacona** [comment]
That is perfect @nwkeeley! Great explanation. I was totally on the right track, but couldn't actually get it to do what I wanted. I also had a funny concurrency issue which I've now resolved.

Thanks for your help!

**Comment by nwkeeley** [comment]
@mplacona glad I could help!

Cheers
