### ISSUE TITLE
Power to the people?

### ISSUE THREAD

**Issue by rschmukler** [rschmukler/agenda#140]
@nwkeeley and @droppedoncaprica do you guys have any interest in having access to publish / write to master? You guys are huge helps in helping me manage this library and I'd really like some way to acknowledge the work you put in.

**Comment by nwkeeley** [comment]
@rschmukler Sure that would be great I appreciate the acknowledgement. Cheers to a great module.

**Comment by droppedoncaprica** [comment]
@rschmukler Sure, I wouldn't mind.  Thanks for the shout-out, glad to help!
