### ISSUE TITLE
Advanced human readable syntax

### ISSUE THREAD

**Issue by ilanbiala** [rschmukler/agenda#143]
I noticed that cron syntax is supported, which seems to support much more than the human readable syntax. How would I be able to do something like every weekday at 9:00 AM with the human readable syntax? Is that possible?

**Comment by droppedoncaprica** [comment]
We use @rschmukler's [human-interval](https://github.com/rschmukler/human-interval) library to parse the readable syntax, so I'd imagine that might be your go-to spot for that one.

**Comment by rschmukler** [comment]
I think that for more advanced usage, cron is fine. If @ilanbiala wants to submit a PR to [date.js](http://github.com/matthewmueller/date) I'm sure @matthewmueller would approve.
