### ISSUE TITLE
Pause Specific Job

### ISSUE THREAD

**Issue by jgallen23** [rschmukler/agenda#144]
Lets say I have a specific job that I've found a bug in.  Is there any way to pause just a specific job and just queue up all requests?  If not is that something you'd take a pull request on?

**Comment by droppedoncaprica** [comment]
I believe you can do this by calling `job.disable()` on the job (and `job.enable()` to re-enable it again).  You'll also have to call `job.save( cb )` to ensure it gets set in the database as well.  [Source](https://github.com/rschmukler/agenda/blob/master/lib/job.js#L115)

Alternatively you should be able to find the job in the DB and manually update the record to have `disabled` set to true, and it shouldn't run.

Let me know if that doesn't work!

**Comment by jgallen23** [comment]
that is on a specific job though, right?  I'd like to be able to do it across the board for future jobs as well.  Something like `agenda.pause('email-notification')` and then agenda will just queue those up instead of actually processing them.

**Comment by droppedoncaprica** [comment]
Yeah, that would be on specific jobs.  You can wholesale disable Agenda using `agenda.stop()`, but that won't be on a per-job basis.

**Comment by jgallen23** [comment]
it looks like `job.disable()` and then `job.save()` actually runs the job.  Is that a bug?

**Comment by droppedoncaprica** [comment]
Well... bug-ish.  

The `job.pause()` method isn't discussed in the README at all, though it is present in the actual code.  If you would like to dive in and see where Agenda isn't respecting the `disabled` attribute when looking up jobs, we can get a PR in.

As of right now though, my time.  It hurts. :frowning:

**Comment by Nishchit14** [comment]
@droppedoncaprica 
`job.pause()` is not present there, firing error of undefined.

Now for pause I've did first `job.disable()` then `job.enable()` on un-pause. But after enabling job, It's not running (I've setup it with every 20 seconds)

After enabling data looks like this
```
    "priority" : 0,
    "nextRunAt" : ISODate("2017-01-12T07:03:32.718Z"),
    "repeatInterval" : "20 seconds",
    "repeatTimezone" : "Asia/Kolkata",
    "lastModifiedBy" : null,
    "lockedAt" : ISODate("2017-01-12T07:04:20.985Z"),
    "lastRunAt" : ISODate("2017-01-12T07:03:12.718Z"),
    "lastFinishedAt" : ISODate("2017-01-12T07:03:12.982Z"),
    "disabled" : false
```

**Comment by PriyaJainDev** [comment]
I tried using `job.disable()` to stop a particular job but seems like the method does not work? Anyone around here who is facing the similar problem?
