### ISSUE TITLE
Passing a mongoose document leads to "Maximum call stack sized exceeded"

### ISSUE THREAD

**Issue by Zertz** [rschmukler/agenda#154]
This is not an issue with agenda itself, but perhaps it should be noted in the docs that passing a mongoose document (which seems like a common use-case) to a job will cause the cryptic "Maximum call stack sized exceeded" exception to be thrown.

The solution is simply to use `doc.toObject();`

**Comment by nwkeeley** [comment]
Just a comment about this if you are using mongoose and don't need specifically need a mongoose object.

collection.find(query, fields, {lean: true}, function(err, doc) {
    //no need to do doc.toObject() the lean option handles this.
});

**Comment by Zertz** [comment]
Yes, depending on the situation, `lean` works too.

I'll close this, the idea was mostly to serve as reference if anyone else runs into this problem.

**Comment by nwkeeley** [comment]
It was good to point out, just wanted to make sure people were aware of the lean option
