### ISSUE TITLE
Schedule Date Format

### ISSUE THREAD

**Issue by killfish** [rschmukler/agenda#174]
From the Readme file: "Schedules a job to run name once at a given time. when can be a **Date** or a String such as tomorrow at 5pm."

What date format should I be using? 
I've tried UNIX timestamps, this format: 2016, January 1, but they don't work.

**Comment by droppedoncaprica** [comment]
I believe you are looking for `new Date(<UNIX timestamp>)`.  Feel free to reopen the issue if this didn't work!

**Comment by killfish** [comment]
That works, thanks!
