### ISSUE TITLE
Request for Agenda Scheduler for Redis

### ISSUE THREAD

**Issue by 0nix** [rschmukler/agenda#188]
The use of MongoDB for a variety of uses that Agenda would be perfect seems like a bit of overkill, as expediency is sacrificed for persistence. I can understand why MongoDB was chosen, but having the option of using Redis would be nice. 

If given enough time, I might actually write a Redis driver for agenda and make a pull request.

**Comment by Zertz** [comment]
Just a suggestion:

> [Kue](https://github.com/Automattic/kue) is a priority job queue backed by redis

**Comment by OmgImAlexis** [comment]
@droppedoncaprica since #309 is more active this can be closed as a dupe.
