### ISSUE TITLE
Is this project still maintained 

### ISSUE THREAD

**Issue by Climax777** [rschmukler/agenda#189]
5 months since last commit. Is this project still being maintained?

**Comment by rschmukler** [comment]
@Climax777 yup. Feel free to submit as many PRs as you'd like :)

**Comment by dandv** [comment]
Can we reopen this issue please?

With 50+ open PRs, and resolved issues [like this](https://github.com/agenda/agenda/issues/745) that haven't been closed, it looks like this project is once again, no longer maintained.

@rschmukler and @simison, have you considered a [Call for help](https://github.com/lukechilds/keyv/issues/71)?

**Comment by OmgImAlexis** [comment]
It is maintained, I recently started a new full time job so I haven’t had much time lately. I hope to get back to this soon.

**Comment by dandv** [comment]
@OmgImAlexis I hope so too, but what about the other maintainers? And are you guys open to accepting new maintainers?
