### ISSUE TITLE
job running with wrong data

### ISSUE THREAD

**Issue by spruce** [rschmukler/agenda#191]
Hello,
using agenda in nearly every project. Thanks for writing it.

My problem is that I have the correct things written to the DB by my web processes, but the job worker don't work correctly. I'm sending some mail via background processes.

in agendaJobs
```
{ "_id" : ObjectId("55e2fd9ecb53efae723824bc"), "name" : "email:paid", "data" : { "ID" : ObjectId("55e2fd74470b2faa72dd6757") }, "type" : "normal", "priority" : 0, "nextRunAt" : null, "lastModifiedBy" : null, "lockedAt" : null, "lastRunAt" : ISODate("2015-08-30T12:57:06.290Z") }
{ "_id" : ObjectId("55e2fd4365dc91aa72836e3d"), "name" : "email:paid", "data" : { "ID" : ObjectId("55e2fcfb1f3961ae729f2a98") }, "type" : "normal", "priority" : 0, "nextRunAt" : null, "lastModifiedBy" : null, "lockedAt" : null, "lastRunAt" : ISODate("2015-08-30T12:55:32.136Z") }
```
as one can see the processes are run at different times with different data. But my logs say it tried to send some mail to the same email adresse:
```
[30.8.15 14:55:34:63] [LOG] sending mail to redacted1@provider.com
[30.8.15 14:57:06:79] [LOG] sending mail to redacted1@provider.com
```
I made sure that the IDs stated in data are in fact two different email adresses in fact they are
```
redacted1@provider.com 
redacted2@provider.de
```

Might this be a problem with multiple job processes? Can you look into that?

**Comment by droppedoncaprica** [comment]
Seeing as the jobs are being saved into the DB correctly, I would think this would be one of two problems.  One possibility is that Agenda's calling the same job multiple times, or that there is some issue with how the job is being called.

Can you verify your job isn't being called twice with the same data?  Logging the data being passed into the job when it runs should let you know if this is the first case or not.

Another thing to look for is how the job is being called; changing the `this` context messes up the arguments the last time I've checked.  Generally speaking, that shouldn't change the saved DB data though. 

Just something to check while you're troubleshooting this.

**Comment by spruce** [comment]
I will log the job.attrs.data now. as you can see I think it is called with the same data twice because it looks up the same email.

What do you mean by changing the this context?

The problem might have been that I didn't call done while providing the callback paramenter. As of late I don't encouter the issue anymore. I think that this still should not happen. Will leave the issue open for some more days. When I don't encouter that anylonger, I consider it my fault. Maybe agenda should log that it waited for done to be called in the console

**Comment by droppedoncaprica** [comment]
What I meant was methods like `fn.call()` `fn.apply()` and `fn.bind()` as far as changing the context.  I didn't communicate very well, sorry.

**Comment by spruce** [comment]
I'm not using any of these functions inside my code related to agenda. simply calling
```javascript
agenda.now('email:paid', {
     bestellungID: dbBestellung._id
});
```
and
```javascript
agenda.define('email:paid', function(job, done) {
...
});
```

Nothing special

**Comment by droppedoncaprica** [comment]
Yup, just saying it's a possibility.

**Comment by spruce** [comment]
So I saw that problem again.
Now as the first thing in the agenda job definition running a console log where it states the correct data. So it probably is a problem with mongoose which finds the wrong item somehow.

Closing now.
