### ISSUE TITLE
job runned twice

### ISSUE THREAD

**Issue by julianusti** [rschmukler/agenda#192]
I have a tasks that needs to be run once per week:

```
var weeklyEmailReport = agenda.schedule('saturday 2pm', 'send email');
weeklyEmailReport.repeatEvery('1 week').save();

var weeklySmsReport = agenda.schedule('monday 12pm', 'send sms');
weeklySmsReport.repeatEvery('1 week').save();
```

it runs them, but runs each single tasks twice(i.e. 'send email' executed two times, instead of one; 'send sms' executed two times, instead of one). I don't understand why? Any ideas?

**Comment by julianusti** [comment]
I think I have found the issue.
From the documentation, where we have an example of how to runt repeadly running tasks:

```
var weeklyReport = agenda.schedule('Saturday at noon', 'send email report', {to: 'another-guy@example.com'});
weeklyReport.repeatEvery('1 week').save();
agenda.start();
```
the `save` function called on agenda creates a copy of task and write in into database.

**Comment by julianusti** [comment]
The `save` function is called twice, based on example.

The first time it's called inside `schedule()` function https://github.com/rschmukler/agenda/commit/a063c6bfee73eb0f5a5c25a8abeb13b23876429d, and the second time I'm calling it according to documentation.

Documentation needs to be corrected, maybe I'll submit pr.

**Comment by julianusti** [comment]
All above is not valid anymore.

The issue is that with the following code:
`agenda.schedule('saturday 2pm', 'send email').repeatEvery('1 week').save();`
agende call `this._db.insert(props, processDbResult);` two times, instead of call it once and then second time call `this._db.findAndModify`

**Comment by rschmukler** [comment]
@julianusti The issue is that `schedule` also calls `save` and so you have a race case where the same job can be saved twice.

The way you should do this:

```js
agenda.create('send email')
  .schedule('saturday at 2pm')
  .repeatEvery('1 week')
  .save();
```

**Comment by julianusti** [comment]
thank you !
