### ISSUE TITLE
Provide a way to turn off event listeners

### ISSUE THREAD

**Issue by jakeorr** [rschmukler/agenda#197]
Agenda has a way to listen for [job queue events](https://github.com/rschmukler/agenda#job-queue-events), but there is no way to remove these event listeners (unless I'm missing something).

i.e.

```
agenda.off('complete');
```

**Comment by rschmukler** [comment]
Would definitely take a PR adding this!

**Comment by jakeorr** [comment]
Whoops, I was missing something. EventEmitter has this [built in](https://nodejs.org/api/events.html#events_emitter_removelistener_event_listener)
