### ISSUE TITLE
Mongoskin update

### ISSUE THREAD

**Issue by jakeorr** [rschmukler/agenda#200]
I would love to see this changed over to use the native mongo driver instead of depending on the `mongoskin` package (which I've seen [talked about](https://github.com/rschmukler/agenda/issues/156)), but as things are, `mongoskin` needs an update.

I'm running node version 4.0.0 and when I include `agenda` I get:

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

Updating to the current version of `mongoskin` (v2.0.0) seems to remove this error, although causes another.

**Comment by jraede** [comment]
+1

**Comment by loris** [comment]
+1

**Comment by jakeorr** [comment]
Not applicable anymore now that mongodb-native is used. (yay!)
