### ISSUE TITLE
Support updated mongoose v4.x with updated mongodb driver v2.x

### ISSUE THREAD

**Issue by sgilroy** [rschmukler/agenda#211]
In my app we use agenda by providing the mongodb collection from mongoose. Something like this:
```
var mongoose = require('mongoose');
var Agenda = require('agenda');
var agenda = new Agenda({ mongo: mongoose.connection.collection('scheduledjobs') });
```

After upgrading to mongoose v4.1.10, I was getting the error `TypeError: Cannot read property 'concurrency' of undefined` because db.findAndModify passes a result to the callback that looks like `{ ok: 1, value: { _id: 'some-id', name: 'some-name' } }` instead of the expected `{ _id: 'some-id', name: 'some-name' }`.

This can be resolved by using the `res.value` instead of `res`.

Looks like this may be the underlying cause of the error reported in #163.

**Comment by wesley-harding** [comment]
:+1: 

I'd really like to see this included.  I've updated mongo/mongoose and I've had to switch to pulling in sgilroy's branch.
