### ISSUE TITLE
config.mongo vs. config.db issue

### ISSUE THREAD

**Issue by fabien** [rschmukler/agenda#225]
It appears that the following:

https://github.com/rschmukler/agenda/blob/master/lib/agenda.js#L39

And this line will be mutually exclusive, while you might need it to specify the collection:

https://github.com/rschmukler/agenda/blob/master/lib/agenda.js#L53

IMHO the correct order should have been:

```
if (config.mongo) {
    ...
} else if (config.db) {
    ...
} else {
    throw new Error('Invalid db configuration');
}
```

**Comment by jakeorr** [comment]
This PR addresses the issue you mention https://github.com/rschmukler/agenda/pull/214

**Comment by Hikariii** [comment]
https://github.com/rschmukler/agenda/pull/234 is merged, containing a solution for this issue

**Comment by rschmukler** [comment]
Thanks!
