### ISSUE TITLE
two or more jobs with same name but different intervals

### ISSUE THREAD

**Issue by pavan612** [rschmukler/agenda#230]
Lets say I have defined a agenda like
    agenda.define('send email', function(job, done) {
          //my own code 
    });
Now I want to run same function with different data for different intervals for example
var array= [{....},{....}];
    array.forEach(function(value){
            agenda.every(5,'seconds','send email');
    });

**Comment by mirkods** [comment]
@pavan612  how do you done it?

**Comment by pavan612** [comment]
ya @mirkods does not find any perfect solution but while creating a job i am saving some attrs for example agenda.create('run workflow', {workflowRuntimeId: workflow_runtimeId,timer: timeInEpcho})

**Comment by mirkods** [comment]
I solved follewed this thread https://github.com/rschmukler/agenda/issues/50
I think this should be good for you as well

**Comment by pavan612** [comment]
+1 @mirkods
