### ISSUE TITLE
Cleanup agenda jobs

### ISSUE THREAD

**Issue by sydneyhenrard** [rschmukler/agenda#233]
Hi, 

I have more than 3K jobs like that:

```
{
    "_id" : ObjectId("56063cbd365cd4030081aae6"),
    "name" : "year-metrics",
    "data" : {
        "year" : 2015
    },
    "type" : "normal",
    "priority" : 0,
    "nextRunAt" : null,
    "lastModifiedBy" : null,
    "lockedAt" : null,
    "lastRunAt" : ISODate("2015-09-26T06:35:41.176Z"),
    "lastFinishedAt" : ISODate("2015-09-26T06:35:41.492Z")
}
```

These jobs are just run once by calling `scheduler.now('year-metrics', {year: year});`. I'd like to remove all unnecessary jobs. I ran `purge` but no job were removed.

So I was wondering if it is the recommended way to remove these jobs:

```
agenda.cancel({nextRunAt: null}, function(err, numRemoved) {
});
```

**Comment by saveman71** [comment]
According to my understanding, `purge` is not what you are looking for because what it does is remove jobs that have a name that does not match a known task (e.g.: you rename a task, and you are left with "orphan" jobs).

I'm also interested in the answer to this issue since I'm currently implementing a newsletter task that then calls `agenda.now` as well for each email.

**Comment by loris** [comment]
Removing finished jobs where `nextRunAt` is null is recommended but you might want to filter out ones which failed (`failedAt` is not null) to properly handled them (like retrying them if it was caused by a network issue, or fix your code if it threw an app exception)

**Comment by Pyrolistical** [comment]
I just use `job.remove` after calling `done()`

**Comment by sydneyhenrard** [comment]
I ended up doing:

```
var Agenda = require('agenda');

var mongoConnectionString = "mongodb://127.0.0.1:27017/mydb";

var agenda = new Agenda({
	db: {address: mongoConnectionString, collection: 'agendaJobs'}
}, function (err) {
	if (err) {
		console.log(err);
		throw err;
	}
	agenda.emit('ready');
	agenda.cancel({nextRunAt: null}, function (err, numRemoved) {
		console.log(err);
		console.log(numRemoved);
	});
});
```

**Comment by saveman71** [comment]
@sydneyhenrard I would have done it like that:

```js
var Agenda = require('agenda');

var mongoConnectionString = "mongodb://127.0.0.1:27017/mydb";

var agenda = new Agenda({
    db: {address: mongoConnectionString, collection: 'agendaJobs'}
}, function (err) {
    if (err) {
        console.log(err);
        throw err;
    }
    agenda.emit('ready');
    agenda.on('success', function(job) {
        job.remove(function(err) {
            if (err) {
                console.log(err);
            }
        });
    });
});
```

That way you don't remove failed jobs, if you ever want to investigate them.

**Comment by tsimbalar** [comment]
Not 100% sure what is the cause, but since updating to `mongo` driver v3.6.4 , it seems that jobs that have already run don't have their `nextRunAt` set to null ... 

Not sure exactly why though :-/
