### ISSUE TITLE
Scaling Question...

### ISSUE THREAD

**Issue by j** [rschmukler/agenda#238]
I have a question... lets say I want to schedule about 100,000 jobs a day to run every hour for a week then stop, can agenda process jobs in the multi-millions?

**Comment by loris** [comment]
The main bottleneck would be MongoDB (and it’s pretty good at handling large number of documents), agenda being a lightweight library built on top of it. In my own experience, I hadn’t had the chance to process multi-million of jobs yet, but from 10k to 100k an hour without any issues.
You should go ahead and tell us how it goes, we might need to optimize some parts (like adding indexes), but i’m pretty confident already.

**Comment by j** [comment]
Hey Loris, I'll let you know how it ends up looking.  :)

**Comment by dziamid** [comment]
@j how did it go with heavy load?
