### ISSUE TITLE
error: uncaughtException: Cannot read property 'topology' of undefined

### ISSUE THREAD

**Issue by niftylettuce** [rschmukler/agenda#242]
I'm initializing agenda like this:

```js
var Agenda = require('agenda');
var connection = mongoose.createConnection(
  config.db.uri,
  config.db.opts
);
var options = { mongo: connection, db: { collection: 'jobs' } };
var agenda = Agenda(options);
```

And I get the error mentioned in this title.

**Comment by niftylettuce** [comment]
I think we need to modify it to be like this:

```diff
+  if ( this._mdb.db.s.topology.connections().length === 0 ) {
-  if ( this._mdb.s.topology.connections().length === 0 ) {
```

It seems `s` is a property of `db` and not `_mdb` for `mongo`.  Maybe we need conditional here to account for both usages?

Per <https://github.com/rschmukler/agenda/blob/master/lib/agenda.js#L380>

**Comment by niftylettuce** [comment]
<https://github.com/rschmukler/agenda/blob/master/lib/agenda.js#L51> needs to be `mdb.db`?

**Comment by niftylettuce** [comment]
I had to upgrade my version of mongodb on my Travis-CI test runner.

Here's how I did it:

`.travis.yml`:

```diff
+# https://github.com/maslennikov/tenge/blob/master/.travis.yml
+# https://travis-ci.org/maslennikov/tenge
+before_script:
+  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
+  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee +/etc/apt/sources.list.d/mongodb.list
+  - sudo apt-get update
+  - sudo apt-get install -y mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6 +mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
+  - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
+  - mongo --version
```

Also in `.travis.yml` I made sure `sudo: true` was set.  This allows us to use `sudo apt-` commands.

**Comment by mathieumg** [comment]
I'm having the same issue on 0.7.6 and the Mongo server is on 3.x.

**Comment by zeitos** [comment]
'agenda/lib/agenda.js:411
  if (this._mdb.s.topology.connections().length === 0) {
               ^

TypeError: Cannot read property 's' of undefined
    at [object Object].Agenda._findAndLockNextJob (/Users/ZeoS/dev/mio/alavaca/alavaca-web/node_modules/agenda/lib/agenda.js:411:16)
    at jobQueueFilling (/Users/ZeoS/dev/mio/alavaca/alavaca-web/node_modules/agenda/lib/agenda.js:592:10)
    at [object Object].processJobs (/Users/ZeoS/dev/mio/alavaca/alavaca-web/node_modules/agenda/lib/agenda.js:470:7)
    at nextTickCallbackWith0Args (node.js:452:9)
'
