### ISSUE TITLE
Running jobs do not get picked back up after restart

### ISSUE THREAD

**Issue by jakeorr** [rschmukler/agenda#255]
I'm running `agenda.stop()` before shutdown of my agenda server and jobs are getting unlocked as expected. Jobs that were currently running are also unlocked, but since they have `nextRunAt: null`, they are not restarted again when the server picks back up. They are essentially lost. Is there a built in way to handle this or is this a case that should be handled in my code?

**Comment by jakeorr** [comment]
I ended up rescheduling one-time jobs on start up like this:

```javascript
var conditions = {
  $or: [{
    nextRunAt: null
  }, {
    nextRunAt: {
      $exists: false
    }
  }],
  $or: [{
    lockedAt: null
  }, {
    lockedAt: {
      $exists: false
    }
  }],
  $or: [{
    lastFinishedAt: null
  }, {
    lastFinishedAt: {
      $exists: false
    }
  }],
  lastRunAt: {
    $ne: null
  }
};

var doc = {
  $set: {
    nextRunAt: new Date()
  }
};

var options = {
  multi: true
};

jobCollection.update(conditions, doc, options, function (err) {});
```

Correct me if I'm wrong, but it seems reasonable that Agenda wouldn't want to automatically start jobs which were in the middle of running when the server was stopped. So doing this in my code seems reasonable.

**Comment by yuniers** [comment]
@jakeorr it means that I must put this code for made that Agenda execute a job when server was stopped.
Can @rschmukler fix it and [add to code](https://github.com/rschmukler/agenda/issues/255#issuecomment-169186392) of new verions?

**Comment by yuniers** [comment]
Maybe adding a ```agenda.update()``` method can resolved the problem.

**Comment by jakeorr** [comment]
Hi @yuniers: sorry, but I'm not totally sure I understand your comment. I'll see if I can give you a useful answer, excuse me if it's not what you were looking for.

I'm using the above code when the server starts up to reschedule any jobs that were currently running when the server was shut down. It has been working for me, but I am not completely confident that it will work in all situations so use it at your own risk. I'm not sure this case is something Agenda should handle internally since jobs that were running when the server shut down could be in a weird state (agenda doesn't know what your job was doing). Seems like something better handled in your app code depending on what your jobs do.

The `jobCollection.update()` call I'm using is a mongo/mongoose call.

**Comment by jakeorr** [comment]
@yuniers I just updated that snippet to fix a big in case you're using it.
