### ISSUE TITLE
feature request: adding times to repeat for every()

### ISSUE THREAD

**Issue by perkd** [rschmukler/agenda#264]
Could we add this?
every(interval, name, [times to repeat], [data], [cb])

job will automatically stop after [times to repeat].

ps. would love to do a PR but just started using agenda for a week, just not sure. thanks!

**Comment by loris** [comment]
As I understand the use case, this looks something pretty unique. Besides, this is something you can already do quite easily by hooking to the `complete` event and storing a complete counter in the `data` field.
here is an example not tested but you’ll get the idea:

```
every(’noon', ’send-email', {to:'foo@bar.com'}, sendEmailHandler);
agenda.on('complete:send-email', function(job) {
  if (job.attrs.data.completeCount >= 5) {
    job.remove();
  } else {
    job.attrs.data.completeCount = (job.attrs.data.completeCount || 0) + 1;
    job.save();
  }
});
```

**Comment by perkd** [comment]
Thanks for the suggestion :)
