### ISSUE TITLE
Dynamically refresh job run time

### ISSUE THREAD

**Issue by swateek** [rschmukler/agenda#270]
I want to change the job run time dynamically.

Let's say jobA is running at every 2 minute. So, for instance, this will run at time like - 01:00, 01:03, 01:05, 01:07 ...

Let's say after the jobA has run at 01:03 I want to change the interval to every 1 minute. I expect it to run next at 01:04.

But currently it runs like - 01:05, 01:06, 01:07...

Any way to refresh the job?

Other things about my application:

- MEAN stack. Job modification is done through application.
- Agenda job is started as a https://www.npmjs.com/package/forever process running as daemon in the background.

**Comment by gumpcha** [comment]
When I've tested it, It doesn't change `nextRunAt` of `agendaJobs` when you restart your process with new interval.

`agenda.cancel` and re-add `agenda.every` will update new interval.

```javascript
  ...
  agenda.cancel({name: 'jobA'}, function(err) {
    agenda.every('* * * * *', 'jobA');
  });
  agenda.start();
  ...
```

**Comment by swateek** [comment]
Great! Thank you so much. This works! :)
