### ISSUE TITLE
options repeatEvery used for?

### ISSUE THREAD

**Issue by raistlinthewiz** [rschmukler/agenda#272]
I have just started using agenda and have the docs, but i couldn't understand one specifc part;

```
every(interval, name, [data, [options]], [cb])

options is an optional argument that will be passed to job.repeatEvery. In order to use this argument, data must also be specified.
```

So what is the options is used for? Any use case examples that can make me understand its usage.

**Comment by jakeorr** [comment]
Have a look at the [section for `.repeatEvery()`](https://github.com/rschmukler/agenda#repeateveryinterval-options). It mentions `options.timezone` which is currently the only option. The section also includes an example.

**Comment by raistlinthewiz** [comment]
thanks!
