### ISSUE TITLE
Agenda performance 

### ISSUE THREAD

**Issue by pavan612** [rschmukler/agenda#274]
Can agenda do thousands or more jobs, can it handle lakhs of jobs, I want to do polling for every minute it may be on different APIs like gmail, capsule, etc can it handle effeciently is it safe to use agenda for this purpose
Thanks

**Comment by loris** [comment]
Yes, go ahead, agenda is just a lightweight library, and the main bottleneck will be MongoDB, so you won’t see any performance limit soon. Like any code querying a database, check that the indexes are properly applied (agenda does it for you)
