### ISSUE TITLE
find jobs completed successfully and failed 

### ISSUE THREAD

**Issue by raistlinthewiz** [rschmukler/agenda#275]
So after every start or set period of time, i'd like to query my database for completed jobs and failed jobs so i can purge them and re-run them.

So what should be the query for completed & failed jobs? 
```
agenda.jobs({name: 'printAnalyticsReport'}, function(err, jobs) {
```

And given after query, i've read how to purge a job, but what about restarting it? Should i re-schedule it basically?

**Comment by loris** [comment]
Here is how I query failed jobs:
`{failedAt:{$exists: true}, nextRunAt: null, $where:'this.failedAt >= this.lastFinishedAt'}`
The best practice though is to hook to `success`, `fail` and `completed` event and do your business logic here (like rescheduling failed jobs, removing completed jobs, etc.)

**Comment by loris** [comment]
To reschedule a job, you just need to update its `nextRunAt` and save it. For instance (using the moment library for date manipulation):
```
agenda.on('fail', (err, job) => {
  job.attrs.nextRunAt = moment().add(10, 'minutes').toDate();
  job.save();
});
```
