### ISSUE TITLE
agenda 0.7.6 - 2nd job instance does not run, but does update lockedAt

### ISSUE THREAD

**Issue by keithrz** [rschmukler/agenda#278]
Steps to Recreate:

1. Define a job
2. Schedule the job twice, so that one scheduled instance runs after the first scheduled instance finishes.
3. When the 2nd scheduled instance should start, the job fields nextRunAt, lastRunAt, and lockedAt should be updated, however, only lockedAt is updated.  And the job never starts.

I have been able to reproduce in agenda 0.7.6, but not in 0.7.5.

**Comment by keithrz** [comment]
Watching this a bit closer, it looks like it will try to start the 2nd scheduled instance after the lock timeout has passed.  In my case, I'm using the default of 10 minutes.

Once the lock timeout has passed, the same thing happens for that 2nd scheduled instance.  The job's lockedAt gets updated, but nextRunAt and lastRunAt do not get updated, and the job doesn't start.

**Comment by jakeorr** [comment]
Version 0.7.7 was just released. Does it solve the problem you are seeing?

**Comment by keithrz** [comment]
Why, yes it does!  I will close this issue.  Thanks!!

**Comment by jakeorr** [comment]
Woop! :+1:
