### ISSUE TITLE
agenda.schedule() API documentation examples are inconsistent

### ISSUE THREAD

**Issue by darkdigitaldream** [rschmukler/agenda#279]
README.md in version https://github.com/rschmukler/agenda/commit/32e70d4d5a56ead05b9413fb69ea3b800d2847a2

has inconsistencies on line 388 and 394. 

on line 374 the API is defined as:
schedule(when, name, [data], cb)

with optional data parameter and required callback.
yet in the examples on line 388 and 394 there is no required callback listed. Without this required callback, the javascript engine assumes the [data] parameter is the callback and throws a type error (not a function)

**Comment by vovka-s** [comment]
+1
Also it should be noted that the callback function has two parameters: error and scheduled job
