### ISSUE TITLE
Prevent certain jobs from running concurrently

### ISSUE THREAD

**Issue by inkadnb** [rschmukler/agenda#293]
Is there a way to prevent certain jobs from executing concurrently?

I have two jobs for different purposes however they sometimes work with the same Mongo collections. One jobs executes once a day, while the other is scheduled based on events.

Because these two jobs are dealing with the same collections, is there a way to keep these jobs from running concurrently?

**Comment by loris** [comment]
You can do that easily on your side: Make both jobs first query your agendaJobs collection, retrieve each others and continue processing only if the other job is not locked (`lockedAt` is null).
