### ISSUE TITLE
working with latest version of aganed and mongo 2.4

### ISSUE THREAD

**Issue by nbukai** [rschmukler/agenda#296]
Hello,

I have just started to work with agenda. The environment I'm working in include mongo version 2.4 which I cannot upgrade. Is there any way to work with latest agenda version and mongo 2.4? 

Thanks for the support.

**Comment by fsamir** [comment]
Check this out:
https://github.com/rschmukler/agenda/pull/334

**Comment by rschmukler** [comment]
Closed by #353
