### ISSUE TITLE
Agenda and Dynamodb

### ISSUE THREAD

**Issue by ajshukury** [rschmukler/agenda#297]
How hard would it be to change MANGO to DYNAMODB? Since we are in AWS environment and would like to DYNAMODB.

**Comment by OmgImAlexis** [comment]
@droppedoncaprica can this please be closed as a dupe of #18

**Comment by simison** [comment]
@dylanjha if you'd like to help, there's now this: https://github.com/agenda/agenda/pull/443

**Comment by dylanjha** [comment]
@simison happy to contribute where I can, but I don't have any use for a dynamo db adapter (or any other db adapter for that matter), nor do I have any experience with dynamo db! (#443) Is there another way I can assist with something?
