### ISSUE TITLE
Save() runs immediately as well

### ISSUE THREAD

**Issue by mirkods** [rschmukler/agenda#298]
Hi there,
I'm having a strange behaviour, this is my code:
```javascript
this.agenda.create(jobName, data)
    .unique({'data.eventId':eventId})
    .repeatEvery(cronString, {timezone:timezone})
    .save(function(err, job){
        res.send(200)
     })
```

Every time that a job is saved its define function is called immediately and then it respects its interval.
Why?

Cheers

**Comment by mirkods** [comment]
@rschmukler I think is strictly related to this https://github.com/rschmukler/agenda/issues/192

**Comment by jakeorr** [comment]
Hi @mirkods. You just need to call `.computeNextRunAt()` before saving:

```javascript
this.agenda.create(jobName, data)
    .repeatEvery(cronString)
    .computeNextRunAt()
    .save(function () {});
```

**Comment by mirkods** [comment]
Thanks @jakeorr!
I think could be useful to add this to the doc.

**Comment by windmaomao** [comment]
to be honest, i think .computeNextRunAt() should be the default case, because if you specify '1 16 * * 2,3,4,5,6', you don't expect it'll run right away.

**Comment by demianhh** [comment]
[frosted-develop.zip](https://github.com/rschmukler/agenda/files/316244/frosted-develop.zip)

**Comment by demianhh** [comment]
![16-06-14-15-59-14-033_photo](https://cloud.githubusercontent.com/assets/18348042/16082802/a85d5b62-32c7-11e6-840c-dd542585367d.jpg)

**Comment by demianhh** [comment]
[this.agenda.create(jobName, data)
    .repeatEvery(cronString)
    .computeNextRunAt()
    .save(function () {});

> ``](url)
