### ISSUE TITLE
mongo driver 2.1 support for Mongodb3.2

### ISSUE THREAD

**Issue by mindfieldx** [rschmukler/agenda#299]
Could be possible upgrade mongodb library to 2.1.x to support Mongodb3.2 ?
Thanks

**Comment by toddbluhm** [comment]
We were having issues with the mongodb driver 2.1.8 in production (I believe agenda uses 2.0.34, but we wanted to be on the same driver across all dependencies) so I forked agenda and bumped it up to 2.1.10 and we seem to be having no issues so far. I would suggest you do something similar until agenda gets updated with the most recent version.

**Comment by ianvonholt** [comment]
As with @toddbluhm, I forked and am running using mongodb at 2.1.15 without problems.

**Comment by fsamir** [comment]
Check this out:
https://github.com/rschmukler/agenda/pull/334

**Comment by joeframbach** [comment]
Related issue: https://github.com/joeframbach/agendash/pull/29/files

**Comment by rschmukler** [comment]
Closed by #353
