### ISSUE TITLE
RepeatEvery accumulates a delay

### ISSUE THREAD

**Issue by mirkods** [rschmukler/agenda#301]
Hi guys,
I noticed that if I define a job that runs every x mins it accumulates a delay because the new date is calculated based on of when it has been completed.
How can avoid this behaviour?

Cheers,
Mirko

**Comment by loris** [comment]
Hi,
can’t repro the issue right now, but according to the code, the new date looks to be calculated based on the `lastRunAt` attributes, which is when the job actually started (`lastFinishedAt` refers to the job completion).

**Comment by mirkods** [comment]
Ok, my mistake
