### ISSUE TITLE
Calling done after saving job data doesn't mark it as completed

### ISSUE THREAD

**Issue by dchapkine** [rschmukler/agenda#308]
Consider this example:
```
agenda.define('example job', {}, function(job, done){
    job.attrs.data.result = {msg: "some result/status text"};
    job.save();
    done();
});
```

The job stays in "running" state and never goes into "completed" state.

How can i attach some data to the job, and after that mark it as completed ?

**Comment by loris** [comment]
`job.save` and `done` are both doing async mongo operations on the job document. So you are having a race condition here.
Use this instead `job.save(done);` to mark the job as completed after your data has been properly attached
