### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by victorbstan** [rschmukler/agenda#323]
Documentation doesn't specify where `new Agenda` is defined, ie: `var Agenda = require('Agenda')`? 

Do Agenda scripts have to be run in a separate node process? ie: `node agenda-script.js` or can they be managed by the same process as an existing node web server (express/restify/etc). In that case, will the Agenda process run as a separate process than the web server, or will the jobs block the web server?

**Comment by manuel-di-iorio** [comment]
You can run Agenda in the same process, jobs are executed async
