### ISSUE TITLE
without mongo db or any database ?

### ISSUE THREAD

**Issue by sivacreatives** [rschmukler/agenda#325]
hi,

can this library be used without mongo db or any database?

If possible to connect, why the below code is not running 

```
var Agenda = require('agenda');
var agenda = new Agenda();

agenda.define('someJob', function(job) {
  console.log('asadad');  
});

agenda.every('3 seconds', 'someJob');
```

Error : TypeError: Cannot read property 'findAndModify' of undefined

**Comment by jotapdiez** [comment]
You can use [node-schedule](https://github.com/mattpat/node-schedule).

**Comment by sivacreatives** [comment]
Thanks for the reply.. I ill close this issue..
