### ISSUE TITLE
Agenda duplicates the jobs into the database, running the same job multiple times

### ISSUE THREAD

**Issue by manuel-di-iorio** [rschmukler/agenda#326]
For some reason and 'randomly', agenda creates multiple records of the same job in the database collection _agendaJobs_, creating the situation where the job is executed multiple times at the same time

![database] (http://i.imgur.com/qGVjYwf.png)

Example code:

    Agenda = require('agenda')

    agenda = new Agenda()
    agenda.defaultConcurrency(1)
    agenda.database("myDB")

    agenda.define 'send notifications', (job, done) ->
        console.log("agenda: job executed at " + new Date().toLocaleString())
        setTimeout(done, 15000) //simulate the task processing

    agenda.on 'ready', ->
        agenda.every('5 minutes', 'send notifications')
        agenda.start()
        console.log('Agenda is ready')

    agenda.on('error', console.error)

Unfortunally, I'm unable to reproduce the issue manually. It **happens** (not rarely) but I'm not already aware of the reason, maybe on some crashes and restart

ps: I'm locally using nodemon but the problem happens even with the process manager of Heroku

**Comment by loris** [comment]
Which job is duplicated? `send notifications` appears only once on your screenshot. Can you show the code where you create the job which get duplicated?

**Comment by manuel-di-iorio** [comment]
`send notifications` was an example, even `check payments` and other tasks gets duplicated as you can see from the screen

My actual code is similar to the first one posted

    Agenda = require 'agenda'

    module.exports = (app) ->
      agenda = new Agenda()
      agenda.defaultConcurrency(1)
      agenda.database 'my db'

      agenda.define 'check payments', (job, done) -> checkPayments done    
      agenda.define 'log txs', (job, done) -> logTxs done
      agenda.define 'send notifications', (job, done) -> sendNotifications done
      
      agenda.on 'ready', ->
        agenda.every '2 minutes', 'send notifications'
        agenda.every '10 minutes', 'check payments'
        agenda.every '30 minutes', 'log txs'
        agenda.start()
        
        console.log 'agenda started'
        
      agenda.on 'error', logger.error

    checkPayments = (done) ->
      today = new Date()
      logger.info "agenda: check payments " + today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds()
      /* my job here */
      done()
      
    logTxs = (done) ->
      today = new Date()
      logger.info "agenda: log txs " + today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds()
      /* my job here */
      done()
      
    sendNotifications = (done) ->
      today = new Date()
      logger.info "agenda: send notifications " + today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds()
      /* my job here */
      done()

**Comment by loris** [comment]
You should add some debug code in the the `agenda.js` file in this part:
```
  } else if (props.type == 'single') {
    if (props.nextRunAt && props.nextRunAt <= now) {
      protect.nextRunAt = props.nextRunAt;
      delete props.nextRunAt;
    }
    if (Object.keys(protect).length > 0) {
      update.$setOnInsert = protect;
    }
    // Try an upsert.
    this._collection.findAndModify({name: props.name, type: 'single'}, {}, update, {upsert: true, new: true}, processDbResult);
```

Using `every` should create `single` job which should only exist once in the database (that’s what the `findAndModify` is supposed to do)

**Comment by manuel-di-iorio** [comment]
Hi, I'm keeping to test Agenda and I confirmed that only the job `check payments` gets duplicated (even after I delete the whole collection)

This is one of the records of that job, as you can see there are no errors:

    {
        "_id": ObjectID("57341b4b8683470fc19e50ff"),
        "name": "check payments",
        "type": "single",
        "data": null,
        "priority": 0,
        "repeatInterval": "10 minutes",
        "repeatTimezone": null,
        "lastModifiedBy": null,
        "nextRunAt": ISODate("2016-05-12T09:08:27.356Z"),
        "lockedAt": null,
        "lastRunAt": ISODate("2016-05-12T08:58:27.356Z"),
        "lastFinishedAt": ISODate("2016-05-12T08:58:27.850Z")
    }

I also moved the call to `done()` at the end of the actual end of the async job, removing any dupt on this front.
Which could be the reason?

**Comment by rawgni** [comment]
did the duplicates happen only when the server restarts ?

**Comment by manuel-di-iorio** [comment]
The problem is that this does not happen "always" on the server restart,
but only some times. I don't know if this is related to server crashes and
relative some race conditions

**Comment by avingochea** [comment]
I used to have this same issue where a job executed multiple times with the /ncb000gt/node-cron package so I switched to this one for scheduling jobs. I just realized Agenda uses the same one as a dependency. I believe the project might be abandoned. It hasn't be updated in quite some time. Might be the same issue?
[https://github.com/ncb000gt/node-cron/issues/180#issuecomment-137097529](url)

**Comment by manuel-di-iorio** [comment]
I close this issue as the problem has not been occurred anymore after almost 3 months of testing, probably was a bug with an old version of Agenda
