### ISSUE TITLE
Remove jobs by unique property

### ISSUE THREAD

**Issue by jdnichollsc** [rschmukler/agenda#329]
Hi man,

Is possible remove a job with a property? like jobId, userId, etc (unique property)

Thanks in advance, Nicholls

**Comment by loris** [comment]
Yes, have a look at the `agenda.cancel` method. FYI, jobs are just simple mongoDb document, so you can also query and remove them like any mongo doc

**Comment by jdnichollsc** [comment]
Add the following example to README.md if you want:

**To create**
```
var job = agenda.create('myJob', { id: 123 });
job.repeatEvery('cronFormathere');
job.unique({ 'data.id': 123 });
job.save();
```

**To remove**
```
agenda.jobs({'name': 'myJob', 'data.id': 123}, function(err, jobs) {
    if(jobs[0]){
        jobs[0].remove();
    }
});
```

Regards, Nicholls

**Comment by loris** [comment]
This is already documented using the `cancel` method: https://github.com/rschmukler/agenda#cancelmongodb-native-query-cb
Thanks
