### ISSUE TITLE
Agenda not running tasks upon restart

### ISSUE THREAD

**Issue by asemoon** [rschmukler/agenda#332]
I have an agenda task that works fine as part of a web app based on sails.js. 
```
var Agenda = require('agenda');
module.exports = function () {
  var mongoConnectionString = "mongodb://127.0.0.1/agenda";
  var agenda = new Agenda({db: {address: mongoConnectionString}, processEvery: '30 seconds'});

  agenda.define('download info', function(job, done) {
     console.info("doing stuff!");
     done();
  });


  agenda.on('ready', function() {
    agenda.every('10 seconds', 'download info');
    agenda.start();
  });

};

```
However, if for any reason the server gets restarted, the job will not start again. It seems like at the end of each call, if the done function is not called, it disrupts the next time this task is scheduled. 
PS: If I delete the entry for the task from the database and rerun the server the task will start working again.

**Comment by sincraianul** [comment]
> if the done function is not called, it disrupts the next time this task is scheduled

Precisely. Agenda locks the task down until `done()` is called or you manually unlock it. The easiest way to unlock all the tasks at once is to intercept the `SIGTERM` and/or `SIGINT` signals that the process may receive, and stop all running tasks:

```javascript
function failGracefully() {
  console.log('Something is gonna blow up.');
  agenda.stop(() => process.exit(0));
}

process.on('SIGTERM', failGracefully);
process.on('SIGINT', failGracefully);
```

Node allows you to handle any standard [POSIX signal](http://man7.org/linux/man-pages/man2/sigaction.2.html) that your process may receive.
