### ISSUE TITLE
lock limit and a lot of queued agenda jobs

### ISSUE THREAD

**Issue by simllll** [rschmukler/agenda#339]
Using the lock limit in combination with a big queue for upcoming jobs (let's say jobs that start in a few days) brings agenda to stop processing any new jobs even if they are already "delayed" or "on-time".

one possible solution would be, that agenda does not lock entries (and queue jobs in the local queue) which are too far in the future. locklimit would still make sense, and the problem with parallel agendas should be also be fine. or does someone have any other ideas? I can offer to implement the fix, but would like to discuss possible other solutions first.

**Comment by jakeorr** [comment]
Hi @simllll. It seems unusual that your jobs scheduled to run in a few days are getting queued at all. Are you using a long `processEvery` interval?

**Comment by simllll** [comment]
Hi @jakeorr , thanks for your quick reply.
I'm using agenda for almost every possible use case I guess:
e.g.: send follow up mails (I'm queuing all follow up mails at the beginning and just in case they are not needed anymore I cancel them). Here we have "simple" non-rescheduling jobs within 3 weeks.

another use case is to send news to users: this is a per user job (every user has it's own agenda job). therefore there are more than 100.000 jobs just for this in there. they have different rescheduling, from one day, up to several weeks (users can change this by their own). could that be the issue? any idea how to do this in a better way?

thanks

**Comment by jakeorr** [comment]
Jobs are only queued if they are scheduled to run before the next processing interval (ie. the next time the database will be checked for jobs to run). The default processing interval is 5 seconds so all of your jobs that are scheduled for more than 5 seconds in the future will not get queued and should not interfere with the lock limit.

**Comment by simllll** [comment]
what about resheduling jobs? do they get "unlocked" again after the have been processed? 
The issue went away as soon as I removed the lockLimit.. it must be somehow related, but I will have a second look then... thanks so far

**Comment by jakeorr** [comment]
I'm not clear on your setup so it's hard get into any details. If you're still having issues, post an example of your job definition.

**Comment by simllll** [comment]
I rewrote some jobs, to be sure that they always call done() (there could be some cicumstance when db connection got lost or so that they haven't called it before).. so far it looks good. Thanks again for your hint.
