### ISSUE TITLE
reschedule after node restart

### ISSUE THREAD

**Issue by ishwarkrishna** [rschmukler/agenda#360]
Agenda is not rescheduling open jobs from database after agenda.start().  Is there any way to do this?

**Comment by ishwarkrishna** [comment]
Did following workaround to get dynamic jobs to start after restart.

...
	agenda.on('ready', function() {
		agenda.jobs({priority: 0}, function(err, jobs) {
			jobs.forEach(function(job) {
				console.log("job Name:",job.attrs.name);
				sampleJob.sendEmail(agenda,job.attrs.name);
			});
		});
	  agenda.start();
	});
...

**Comment by simison** [comment]
Dublicate? #131  #175

**Comment by OmgImAlexis** [comment]
As @simison stated this looks like a dupe.

@droppedoncaprica can you please close.
