### ISSUE TITLE
Appointment Scheduler usecase

### ISSUE THREAD

**Issue by noisyox** [rschmukler/agenda#362]
Sorry for asking implementation questions here as I am unable to find any google groups on agenda.

I need to implement the notify user about the appointment schedule which was created by them similar to email scheduled by each user with different data on different time. 

- Do I need to set cron for all the appointment schedules. If yes, how to pass the job specific arguments?

- Is there a better implementation, example?

I am using pub nub for notification service, I need to understand if cron is the better way to fire the notification service as there will be different notification text to different user  / same user every time.

Thanks in advance.

**Comment by loris** [comment]
No, you don't need to set cron. Here is the correct implementation:

First define, the job business logic:

```
agenda.define('notify-user-about-appointment', function(job, done) {
  var data = job.attrs.data;
  // data will contain the user specific data (the one passed in the `agenda.schedule` call below)
  // add here the pubnub notification logic, and call `done`
});
```

Then, whenever a user ask to be notified:
```
 var jobDate = new Date(); // whenever you want the job to fire
 var jobData = {to: 'admin@example.com'}; // any data about the user you will need to send the notification
 agenda.schedule(jobDate, 'notify-user-about-appointment', jobData);
```

**Comment by noisyox** [comment]
@loris Hey, thank you for your quick prompt.

If there are n number of appointment reminders then i have to set n number of times **agenda.schedule** with appropriate data-set for appointment reminder, right?

Can I set the recurring schedule in same way?  

Need help: As I am new to node.js been research regarding the same I found two approach 

- Schedule a cron: agenda or schedule
- use redis backed queue: [link](https://hashnode.com/post/how-to-build-a-robust-system-for-scheduling-notifications-in-nodejs-ciobsjhtr0084mt530cmfoy5o#ciobtrnk3007rm1533197w7na)

Do you see any pro or con over the other approach? kindly guide me.
