### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by swapnil001** [rschmukler/agenda#377]
Hi,

Suppose I have a job running after every 5 seconds, and the first one is not finished yet then will second process start running or because of locktime, my second process won't run?

**Comment by danibjor** [comment]
I have multiple concurrent jobs overlapping - and the logs show they start when they are scheduled. So, no delay or locking.

**Comment by OmgImAlexis** [comment]
@droppedoncaprica can this please be closed as it's a question which has been answered.
