### ISSUE TITLE
Dynamically Reschedule Agenda Jobs

### ISSUE THREAD

**Issue by swateek** [rschmukler/agenda#381]
I want to modify a scheduled Agenda Job through my code.

Is it only the "repeatInterval" and "nextRunAt" in the job collection that needs to be modified? Or is there a cleaner way to do the same?

**Comment by mariokam** [comment]
Hey, the same here. Any solution?

**Comment by swateek** [comment]
The idea is - when you reschedule jobs you need to do it programatically. Cancel the existing one and create another one when the time is modified.

I don't have a solution to this, using node-scheduler with a custom framework instead.
