### ISSUE TITLE
Agenda v0.9.0 publishing problem

### ISSUE THREAD

**Issue by kerimdzhanov** [rschmukler/agenda#395]
There are difference between v0.9.0 that is published in the NPM repo and v0.9.0 that is in github repo.

In the npm version 0.9.0 was published 5 month ago, but in github it's released 16 days ago.

And sure that the source code and changelog are different as well.

The npm package's changelog:
```
0.9.0 / 2016-08-13
==================
  * Upgrade mongo driver to 2.1.11
  * Increase Mongo compatability to 2.4
```

The github's release changelog:
```
0.9.0 / 2016-12-28
==================
  * add support for mongoose.connection for agenda.mongo(), fixes #156
  * Fix for race condition in the afterEach clean up code (#355)
  * Fixes + protects against concurrency not being honored (#379)
  * Bump mongodb dep version to support ssl conns (#368)
  * Increase Mongo compatability to 2.4
```

Can you release and re-publish agenda again? Thanks in advance!

**Comment by galniv** [comment]
Bump. This is still an issue. It will be especially helpful to have a tagged version that includes the fix for #379.

**Comment by netputer** [comment]
Ping @rschmukler

**Comment by Santas** [comment]
+1

**Comment by westrem** [comment]
+1

**Comment by jdmunro** [comment]
Also impacted by this. Looks like maybe the original maintainer is no longer active on this project.

**Comment by thekarel** [comment]
@jdmunro You can pass in your own mongo client to Agenda so it won't use its own outdated module:

```
const startAgenda = (mongo) => {
    const agenda = new Agenda({mongo})

    agenda.start()
}
```

Works fine with Mongo 3.4.

**Comment by simison** [comment]
Maintainers needed? https://github.com/rschmukler/agenda/issues/414

**Comment by rschmukler** [comment]
Hey all. I'm so terribly sorry for the delay on this. I have republished under `agenda@0.9.1`. Feel free to follow along in #414 discussing how we can improve this.
