### ISSUE TITLE
Running new Jobs after server started

### ISSUE THREAD

**Issue by harriswilliam** [rschmukler/agenda#427]
I run my server and execute jobs that are already saved in database (agendaJobs collection ).

But if I add new jobs in database while server is already started, they are not executed.

How can I let it execute ?

**Comment by carrbrpoa** [comment]
Maybe I have the same doubt:

Let's consider this code:

```
agenda.define('say hello', function (job, done) {
	console.log('Hello ' + new Date());
	done();
});

agenda.on('ready', function () {
	console.log('Agenda ready');

	agenda.jobs({
		name: 'say hello'
	}, function (err, jobs) {
		console.log('verificando jobs');
		
		if (!jobs || jobs.length === 0) {
			var sayHello = agenda.create('say hello');
			sayHello.repeatEvery('3 seconds').save();
		} else {
			console.log('já existe o job');
			sayHello = jobs[0];
			sayHello.repeatEvery('3 seconds').save();
		}

		agenda.start();
		console.log('started');
	});
});
```

I run it for the first time - OK. If I restart the server some time after, I expected the job restarted it's `console.log` job, but that don't happen. What am I doing wrong?

Thanks

**Comment by harriswilliam** [comment]
Hello, 
I think your code is working. 

You notice that your console.log take several time to happen. The reason is that the "nextRunAt" date of the job is already in the past when your server is restarted. So agenda has an internal routine to run it with a certain delay. I don't know what is this delay or how to set it, but that's it.

That's my opinion

**Comment by carrbrpoa** [comment]
@harriswilliam you were right, it seems to be [defaultLockTime](https://github.com/rschmukler/agenda/blob/050d7455633ba747da0a70d24a5eb06b8624c797/README.md#defaultlocklifetimenumber), since the restart time I noticed was about 10 minutes. Changed it to 10000 (10 seconds) to test and server restart resumes the job almost instantly.

About the code you suggested, it says `TypeError: jobs[i].toObject is not a function`. Do I need another dependency?

Thanks

**Comment by carrbrpoa** [comment]
Well, guess I can just take `jobs[i]`:

![image](https://cloud.githubusercontent.com/assets/10212618/26105627/0e5e7df2-3a19-11e7-91d7-6368137cd207.png)

:D

**Comment by harriswilliam** [comment]
Nice!!

I used "jobs[i].toObject();" because for some reason that I don't really understand, I can't access the data of the job object.

May be it is according the way I get my object from database. I didn't use "agenda.jobs" to get jobs object, but I used mongoose search methods directly.
