### ISSUE TITLE
Map Agenda on a replicat set

### ISSUE THREAD

**Issue by geo1004** [rschmukler/agenda#86]
Hi,

I would like to deploy Agenda on my production environment. 
Is there any special configurations to connect it on a replicat set? 
The replicat set is load balanced on three different servers. Each mongo instance has a basic authentication by login/password.
I've tried 
```javascript
mongoUrl = 'mongodb://login:password@myIpAddress1:myPort,login:password@myIpAddress2:myPort,login:password@myIpAddress3:myPort/agenda_analytics'

agenda = new Agenda {
  db:
    address: mongoUrl
    collection: 'agendaJobs'
}
```
I've got a mongodb error: Auth failed. I use the same connect string to connect node.js to my replicat set and it works. 
Any idea what can be the problem?

Thank you
Geo

**Comment by t0lkman** [comment]
any updates on that?

**Comment by nwkeeley** [comment]
I also connect to a replica set with Agenda without any issues. Like droppedoncaprica I did not specify a collection name and allowed it to default to agendaJobs.

@geo1004  Can you confirm if this is still an open issue for you?

**Comment by droppedoncaprica** [comment]
Just to chime in, this should be using the normal connection string settings found here:

http://docs.mongodb.org/manual/reference/connection-string/

**Comment by mleanos** [comment]
This issue seems to be related to an issue I'm experiencing. But most likely not the exact issue.

My Agenda worker seems to connect fine when using the format `mongodb://<dbuser>:<dbpassword>@ds358744.mongolab.com:433333/dbname`

However, what I'd like to do is this 

`{ address: 'mongodb://ds358744.mongolab.com:433333/dbname ', collection: 'agendaJobs', options: { user: 'loginname', pass: 'password'} }`

Perhaps, mongoskin doesn't support these options? I'm trying to figure that out now.

**Comment by geo1004** [comment]
Sorry I've just seen all these updates, it's a very old issue. Sorry I can't give you any update, my job has changed several times since and I don't have access to the project anymore. I let the issue open, others seems to also have some troubles.

**Comment by irtazabbas** [comment]
the issue persists

**Comment by loris** [comment]
Can you provide us with more info? (Agenda version and agenda init code)

**Comment by irtazabbas** [comment]
version `0.8.0`
``` connectionString = 'mongodb://username:passwordi@heroku_5ktvtxdx:kd2j58s00so0qhs0o1j2r16o79@ds019680-a0.mlab.com:19680,ds019680-a1.mlab.com:19680/dbname'; 
var agenda = new Agenda({db: {address: connectionString}});
//tried with
//agenda.database(connectionString);
//var agenda = new Agenda({db: {address: connectionString, collection: 'myJobs'}});```

**Comment by loris** [comment]
And how is it behaving? any error thrown?
Has your app already established a db connection before (like with Mongoose)?

Anyway it should not be an issue with Agenda itself, but with the init script. I’m using agenda `0.8.0` with a replica set from mlab too, and it’s working fine.

**Comment by irtazabbas** [comment]
here is the error 
```
node_modules/agenda/node_modules/mongodb/lib/server.js:228
        process.nextTick(function() { throw err; })
                                      ^
Error: getaddrinfo ENOTFOUND dbname dbname:27017
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

**Comment by loris** [comment]
Hum, agenda is trying to connect to `dbname:27017`? You should check what `connectionString` you are passing to agenda (add some `console.log` in `node_modules/agenda/lib/agenda.js`) because it looks like you are not passing the right variable

**Comment by irtazabbas** [comment]
inserted `console.log('agenda url', url)` [here](https://github.com/rschmukler/agenda/blob/master/lib/agenda.js#L77) and got
```
agenda url:  mongodb://user:password@heroku_5ktvtxdx:kd2j58s00so0qhs0o1j2r16o79@ds019680-a0.mlab.com:19680,ds019680-a1.mlab.com:19680/dbname
```
got the same error as above. And yes the same connection string works with mongoose.

**Comment by loris** [comment]
Your connection string is not valid (you have two `@` chars), so the mongo driver can’t parse it and default to localhost. By the way, you should edit your previous comments, you plain username and password are included :(

**Comment by irtazabbas** [comment]
@loris Thanks. So that url format was supported by mongoose but not by `mongodb` which uses `url.parse()` that throws the exception. So the format below worked. Thanks.
```
var connectionString = 'mongodb://user:password@ds019680-a0.mlab.com:19680,ds019680-a1.mlab.com:19680/dbname';
```
